service: api-culteur

provider:
  name: aws
  runtime: nodejs6.10

functions:
  users.post:
    handler: src/handler.api
    events:
      - http: 'POST /users'


plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - node_modules/**/*
  include:
    src/handler.ts